import type { StatCard, ActivityItem, Project, TeamMember, ChartDataPoint } from '@/types';

export const statCards: StatCard[] = [
  {
    id: '1',
    title: 'Total Revenue',
    value: '$84,320',
    change: 12.5,
    changeLabel: 'vs last month',
    gradient: 'linear-gradient(135deg, #6c63ff 0%, #8b5cf6 100%)',
    icon: 'dollar',
  },
  {
    id: '2',
    title: 'Active Users',
    value: '24,891',
    change: 8.2,
    changeLabel: 'vs last week',
    gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    icon: 'users',
  },
  {
    id: '3',
    title: 'New Orders',
    value: '3,247',
    change: -2.4,
    changeLabel: 'vs yesterday',
    gradient: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    icon: 'shopping',
  },
  {
    id: '4',
    title: 'Conversion Rate',
    value: '5.63%',
    change: 1.8,
    changeLabel: 'vs last month',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
    icon: 'chart',
  },
];

export const recentActivity: ActivityItem[] = [
  {
    id: '1',
    user: 'Alex Chen',
    avatar: 'AC',
    action: 'pushed code to',
    target: 'main branch',
    time: '2m ago',
    type: 'commit',
  },
  {
    id: '2',
    user: 'Sarah Kim',
    avatar: 'SK',
    action: 'reviewed PR',
    target: '#142 Feature Auth',
    time: '15m ago',
    type: 'review',
  },
  {
    id: '3',
    user: 'Marcus Webb',
    avatar: 'MW',
    action: 'deployed',
    target: 'v2.4.1 to production',
    time: '1h ago',
    type: 'deploy',
  },
  {
    id: '4',
    user: 'Priya Patel',
    avatar: 'PP',
    action: 'opened issue',
    target: '#201 Performance Bug',
    time: '2h ago',
    type: 'issue',
  },
  {
    id: '5',
    user: 'Jordan Lee',
    avatar: 'JL',
    action: 'commented on',
    target: 'API Design Spec',
    time: '3h ago',
    type: 'comment',
  },
  {
    id: '6',
    user: 'Emma Davis',
    avatar: 'ED',
    action: 'completed task',
    target: 'Database Migration',
    time: '4h ago',
    type: 'deploy',
  },
];

export const projects: Project[] = [
  {
    id: '1',
    name: 'Aurora Platform',
    description: 'Next-gen cloud infrastructure platform with auto-scaling capabilities',
    progress: 72,
    status: 'active',
    team: ['AC', 'SK', 'MW', 'PP'],
    dueDate: 'Mar 15, 2025',
    tasks: 48,
    completedTasks: 35,
    color: '#6c63ff',
  },
  {
    id: '2',
    name: 'Nexus API',
    description: 'Unified API gateway for microservices communication',
    progress: 45,
    status: 'active',
    team: ['JL', 'ED', 'AC'],
    dueDate: 'Apr 2, 2025',
    tasks: 32,
    completedTasks: 14,
    color: '#10b981',
  },
  {
    id: '3',
    name: 'DataVault',
    description: 'Secure data warehouse solution with real-time analytics',
    progress: 91,
    status: 'active',
    team: ['SK', 'PP', 'MW'],
    dueDate: 'Feb 28, 2025',
    tasks: 60,
    completedTasks: 55,
    color: '#3b82f6',
  },
  {
    id: '4',
    name: 'Pulse Mobile',
    description: 'Cross-platform mobile app for team communication',
    progress: 28,
    status: 'paused',
    team: ['ED', 'JL'],
    dueDate: 'May 20, 2025',
    tasks: 24,
    completedTasks: 7,
    color: '#f59e0b',
  },
  {
    id: '5',
    name: 'Orbit Design System',
    description: 'Company-wide design system and component library',
    progress: 100,
    status: 'completed',
    team: ['AC', 'SK', 'ED', 'JL', 'MW'],
    dueDate: 'Jan 10, 2025',
    tasks: 40,
    completedTasks: 40,
    color: '#ec4899',
  },
  {
    id: '6',
    name: 'ShieldAuth',
    description: 'Enterprise authentication and authorization framework',
    progress: 58,
    status: 'active',
    team: ['PP', 'MW', 'AC'],
    dueDate: 'Mar 30, 2025',
    tasks: 36,
    completedTasks: 21,
    color: '#06b6d4',
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Alex Chen',
    role: 'Lead Engineer',
    avatar: 'AC',
    status: 'online',
    email: 'alex.chen@company.io',
    projects: 4,
    tasks: 12,
    joined: 'Jan 2022',
  },
  {
    id: '2',
    name: 'Sarah Kim',
    role: 'Product Designer',
    avatar: 'SK',
    status: 'online',
    email: 'sarah.kim@company.io',
    projects: 3,
    tasks: 8,
    joined: 'Mar 2022',
  },
  {
    id: '3',
    name: 'Marcus Webb',
    role: 'DevOps Engineer',
    avatar: 'MW',
    status: 'busy',
    email: 'marcus.webb@company.io',
    projects: 4,
    tasks: 15,
    joined: 'Jun 2021',
  },
  {
    id: '4',
    name: 'Priya Patel',
    role: 'Backend Engineer',
    avatar: 'PP',
    status: 'away',
    email: 'priya.patel@company.io',
    projects: 3,
    tasks: 10,
    joined: 'Sep 2022',
  },
  {
    id: '5',
    name: 'Jordan Lee',
    role: 'Frontend Engineer',
    avatar: 'JL',
    status: 'offline',
    email: 'jordan.lee@company.io',
    projects: 2,
    tasks: 9,
    joined: 'Nov 2022',
  },
  {
    id: '6',
    name: 'Emma Davis',
    role: 'Data Engineer',
    avatar: 'ED',
    status: 'online',
    email: 'emma.davis@company.io',
    projects: 2,
    tasks: 6,
    joined: 'Feb 2023',
  },
];

export const revenueData: ChartDataPoint[] = [
  { label: 'Jan', value: 42000, secondaryValue: 35000 },
  { label: 'Feb', value: 58000, secondaryValue: 48000 },
  { label: 'Mar', value: 51000, secondaryValue: 42000 },
  { label: 'Apr', value: 67000, secondaryValue: 55000 },
  { label: 'May', value: 73000, secondaryValue: 61000 },
  { label: 'Jun', value: 64000, secondaryValue: 58000 },
  { label: 'Jul', value: 81000, secondaryValue: 70000 },
  { label: 'Aug', value: 79000, secondaryValue: 68000 },
  { label: 'Sep', value: 90000, secondaryValue: 75000 },
  { label: 'Oct', value: 84000, secondaryValue: 72000 },
  { label: 'Nov', value: 95000, secondaryValue: 80000 },
  { label: 'Dec', value: 102000, secondaryValue: 88000 },
];

export const trafficData: ChartDataPoint[] = [
  { label: 'Mon', value: 3200 },
  { label: 'Tue', value: 4100 },
  { label: 'Wed', value: 3800 },
  { label: 'Thu', value: 5200 },
  { label: 'Fri', value: 4800 },
  { label: 'Sat', value: 2900 },
  { label: 'Sun', value: 2400 },
];
